### ISSUE TITLE
use six.string_types to check for strings

### ISSUE THREAD

**Issue by greg-latuszek** [nokia/moler#13]
@marcin-usielski see: https://github.com/nokia/moler/blob/master/moler/cmd/commandtextualgeneric.py#L60

instead of:
```
        if sys.version_info >= (3, 0):
            if isinstance(prompt, str):
                prompt = re.compile(prompt)
        else:
            if isinstance(prompt, basestring):
                prompt = re.compile(prompt)
```
you can write it simpler via:
```
import six

        if isinstance(prompt, six.string_types):
            prompt = re.compile(prompt)
```

**Comment by marcin-usielski** [comment]
@greg-latuszek 
I'm not sure if simplifying so easy code is worth depending on external Python library. And simplifying is not so obvious - reader must know something about six.

**Comment by greg-latuszek** [comment]
We are already dependent - used inside connection, connection_observer, memory, runner

and six is "the most standard way" to keep Py2-Py3 compatibility.

and simplification is worth - if-s are hidden inside six library.

**Comment by emcek** [comment]
I agree with Greg! Anyway I'm voting for remove py2 support, but it is impossible right now.

**Comment by marcin-usielski** [comment]
OK. I'm convinced.

**Comment by marcin-usielski** [comment]
Done. Available on master.
