### ISSUE TITLE
add CHANGELOG.md

### ISSUE THREAD

**Issue by greg-latuszek** [nokia/moler#250]
follow:
https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md
https://keepachangelog.com/en/1.0.0/
https://semver.org/spec/v2.0.0.html

use patterns from:
https://pypi.org/project/pytest/5.3.1/
https://docs.pytest.org/en/latest/changelog.html

**Comment by akubala** [comment]
@greg-latuszek , in our **Moler release v1.3.0** we have added **CHANGELOG.md** 👍
