### ISSUE TITLE
include CHANGELOG.md inside README.md

### ISSUE THREAD

**Issue by greg-latuszek** [nokia/moler#257]
Documentation at https://pypi.org/project/moler/ as well as the one visible at https://github.com/nokia/moler is not refering CHANGELOG.md in any way.

To see it you need direct jump into https://github.com/nokia/moler/blob/master/CHANGELOG.md
But you need to know that such file exists.

Would be great to have it like https://pypi.org/project/pytest/  (search Changelog)

**Comment by akubala** [comment]
@greg-latuszek , in our latest **Moler release v1.3.1**, we have included reference to **CHANGELOG.md** 👍
