### ISSUE TITLE
Incorrect class name defined in 'my_devices.yml' example file

### ISSUE THREAD

**Issue by bullsbb** [nokia/moler#342]
Content of example configuration file - my_devices.yml are as below: 
======================================================================
How does it know what 'MyMachine' means? Code loads definition from my_devices.yml configuration file:

    DEVICES:

      MyMachine:
        DEVICE_CLASS: moler.device.unixremote.UnixLocal
======================================================================

"DEVICE_CLASS" defined for 'MyMachine' is incorrect. It should be:
======================================================================
How does it know what 'MyMachine' means? Code loads definition from my_devices.yml configuration file:

    DEVICES:

      MyMachine:
        DEVICE_CLASS: moler.device.unixlocal.UnixLocal
======================================================================

**Comment by Ernold11** [comment]
MyMachine is just friendly name for defined device, which you can use to connect to get and use device in your python scripts.

**Comment by bullsbb** [comment]
> MyMachine is just friendly name for defined device, which you can use to connect to get and use device in your python scripts.

Thanks for responding. What I meant is 'DEVICE_CLASS' is wrongly defined for 'MyMachine':

Current definition:  

DEVICES:

  MyMachine:
    DEVICE_CLASS: moler.device.**unixremote**.UnixLocal

Correct one should be:

DEVICES:

  MyMachine:
    DEVICE_CLASS: moler.device.**unixlocal**.UnixLocal

The example file **moler-master/examples/command/unix_ps.py** can't be executed correctly with the current incorrect configuration defined in **moler-master/examples/command/my_devices.yml**.

**Comment by Ernold11** [comment]
Yes and no.
Yes because definition of UnixLocal so console on your local computer is provided by class moler.device.**unixlocal**.UnixLocal.
No because **UnixRemote** inherits from **UnixLocal** and also have state **UnixLocal** so this definition will also work.
But we strongly recommend to use as you wrote moler.device.**unixlocal**.UnixLocal because code look a lot better and not tricky.
